### ISSUE TITLE
Are you considering changing internationalization language to optional?

### ISSUE THREAD

**Issue by ifredom** [VictorUvarov/provider_architecture_template#11]
For my project, there is no need for multiple languages, which makes the dialog unavailable。

Are you considering changing internationalization language to optional?

**Comment by VictorUvarov** [comment]
Currently it will default to the first language in the list of locals, which you can have as only English. To just use hard coded strings you would have to have the Dialog and Snackbar not use local.translate(). I'm sure just having a flag in the AlertRequest/SnackBarRequest for translate will do the trick.

**Comment by ifredom** [comment]
Yes I tried it, I manually removed the multi-language
