### ISSUE TITLE
[question] This provider architecture works for BLoC pattern?

### ISSUE THREAD

**Issue by vinothvino42** [VictorUvarov/provider_architecture_template#22]
I'm planning to implement this architecture for BLoC and I want to know whether this structure suits for BLoC pattern and the project need to be testable?

**Comment by VictorUvarov** [comment]
Yeah you can use the Bloc pattern with the folder structure. Replace view models with blocs, replace view model providers with Bloc providers, etc...

**Comment by vinothvino42** [comment]
Thank you so much. I thought it was a silly question so I closed the issue but I really liked your architecture so I just reopened it.
