### ISSUE TITLE
It is recommended to upgrade the provider_architecture to stacked

### ISSUE THREAD

**Issue by ifredom** [VictorUvarov/provider_architecture_template#24]
It is recommended to upgrade the `provider_architecture` to `stacks`

**Comment by Prn-Ice** [comment]
I think he is, check [here](https://github.com/VictorUvarov/provider_immutable_state).

**Comment by VictorUvarov** [comment]
Yeah I'll try to update the dependency soon. Haven't been able to run the project since Hive wasn't working with the new flutter version.
