### ISSUE TITLE
Why Immutable State?

### ISSUE THREAD

**Issue by Prn-Ice** [VictorUvarov/provider_architecture_template#33]
Hi @VictorUvarov I use the stacked architecture and I also follow up updates in your architecture from time to time but I'm confused about the immutable state. This is the first time I'm seeing it implemented, do you have links to resources that can help me get started.

**Comment by VictorUvarov** [comment]
The idea around immutable state is that the UI will only ever be in one state and all the states are known. For example one page could be in the loading state, but there are loading, loaded, and error state. 
- Reso coder gave a talk about it here https://www.youtube.com/watch?v=4UePKj4vsK8. Another benefit of immutable state is the UI will only be given data that it needs. For example, the loading state in a PostsView won't have access to the posts when it is loading. 
- Only when the state is loaded, then the UI will have access to the posts. This is something i'm still experimenting with provider.

**Comment by Prn-Ice** [comment]
Thanks for clarifying. Will watch the video, feel free to close this issue.
