### ISSUE TITLE
Can't seem to run this project

### ISSUE THREAD

**Issue by ghedwards** [VictorUvarov/provider_architecture_template#35]
![image](https://user-images.githubusercontent.com/125586/84454732-c9487280-ac9e-11ea-976c-05affb323e9b.png)

I've run flutter create . and checked the SdkVersion settings in build.gradle ( 28 ) , any ideas ?

**Comment by ghedwards** [comment]
Stack trace looks something like this..
![image](https://user-images.githubusercontent.com/125586/84454861-1298c200-ac9f-11ea-8a20-03f0483e9556.png)

**Comment by VictorUvarov** [comment]
Can you do a flutter doctor -v. I've only tested this repository on the flutter stable branch.

**Comment by ghedwards** [comment]
Running stable channel, no other project has trouble, not sure what's happening.

![image](https://user-images.githubusercontent.com/125586/84862413-7c0d3c00-b0b6-11ea-8715-39c6da74f390.png)

![image](https://user-images.githubusercontent.com/125586/84862479-98a97400-b0b6-11ea-9208-a8dc4a326fcb.png)

**Comment by ghedwards** [comment]
I ran "flutter pub upgrade" and it seems to have come good.
