### ISSUE TITLE
How to use navigation service with dialog?

### ISSUE THREAD

**Issue by ifredom** [VictorUvarov/provider_architecture_template#8]
`
    onTap: () {
            showDialog(
                  context: context,
                  barrierDismissible: false,
                  builder: (_) => SettingPage(),
            );
    },

`

in SettingPage dialog , i cant' use

`
locator<NavigationService>().pop();
`
and replace .i must use:
`
Navigator.of(context).pop();
`

but I want to use it all  *locator<NavigationService>().pop();*  ，  how to Solve it ?

**Comment by VictorUvarov** [comment]
The dialog service has its own [navigator key](https://github.com/VictorUvarov/provider_architecture_template/blob/master/lib/core/services/dialog/dialog_service_impl.dart#L10). If you notice in the dialog manager shows a [dialog](https://github.com/VictorUvarov/provider_architecture_template/blob/master/lib/core/managers/dialog_manager.dart#L45) that will handle the provided onConfirmed and onDenied callbacks. Those callbacks trigger the dialog to [pop](https://github.com/VictorUvarov/provider_architecture_template/blob/master/lib/core/services/dialog/dialog_service_impl.dart#L34) when it receives a response. All you need to do is create a similar dialog that is in the dialog manager.

**Comment by ifredom** [comment]
> The dialog service has its own [navigator key](https://github.com/VictorUvarov/provider_architecture_template/blob/master/lib/core/services/dialog/dialog_service_impl.dart#L10). If you notice in the dialog manager shows a [dialog](https://github.com/VictorUvarov/provider_architecture_template/blob/master/lib/core/managers/dialog_manager.dart#L45) that will handle the provided onConfirmed and onDenied callbacks. Those callbacks trigger the dialog to [pop](https://github.com/VictorUvarov/provider_architecture_template/blob/master/lib/core/services/dialog/dialog_service_impl.dart#L34) when it receives a response. All you need to do is create a similar dialog that is in the dialog manager.

Thank you for your work. I see. I'll try
